repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-encoding-pragma
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        name: fix markdown formatting with mdformat
        types: [markdown]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-toc
          - mdformat-frontmatter
  - repo: 'https://github.com/antonbabenko/pre-commit-terraform'
    rev: v1.75.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
